name: ivanconcept
favicon: null
layout_spectrum: 0.6998314
typography_spectrum: 0.89417
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ivanconcept
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#267fff'
    - '#a7a7a7'
    - '#5f5f5f'
  brandStrength: 0.5
  lightness: 0.6347776257898659
  saturation: 0.4812696781009436
  rhythmicContrast: 0
purpose: []
