name: ivanconcept
favicon: null
layout_spectrum: 0.49843
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Ivan Wong, Pianist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08060a'
    - '#201f27'
    - '#e47c6b'
    - '#e2c7be'
    - '#353746'
  brandStrength: 0
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 1
purpose: []
