typography_spectrum: 1
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.5740092233754694
  lightness: 0.3939265822991729
  saturation: 0.5517122449818999
  rhythmicContrast: 0.47638259548693895
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6430063715670258
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf646612-d5eb-4775-b4f6-02fbf130f8fa.png
name: ivanconcept
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Ivan Wong
description: Inspiring greater music.
purpose: []
